# Generated by Django 3.0.7 on 2020-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='заголовок объявления')),
                ('text', models.TextField(max_length=1000, verbose_name='текст')),
                ('category', models.CharField(choices=[('1', 'Автомобили (покупка)'), ('2', 'Автомобили (продажа)'), ('3', 'Автомобили (сервис)'), ('4', 'Бытовая техника (услуги)')], max_length=1, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
    ]
