# Generated by Django 3.0.7 on 2020-07-17 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200716_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kerchent_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Аккаунт керчьнет',
                'verbose_name_plural': 'Аккаунты керчьнета',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Автомобили (покупка)'), ('2', 'Автомобили (продажа)'), ('3', 'Автомобили (сервис)'), ('4', 'Бытовая техника (услуги)')], max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок объявления'),
        ),
    ]
