# Generated by Django 3.0.7 on 2020-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200720_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerchnet_account',
            name='ka_email',
            field=models.EmailField(default=2, max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
