# Generated by Django 3.0.7 on 2020-07-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_kerchnet_account_ka_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kerchnet_account',
            old_name='ka_datetime_created',
            new_name='kn_datetime_created',
        ),
        migrations.RenameField(
            model_name='kerchnet_account',
            old_name='ka_email',
            new_name='kn_email',
        ),
        migrations.RenameField(
            model_name='kerchnet_account',
            old_name='ka_login',
            new_name='kn_login',
        ),
        migrations.RenameField(
            model_name='kerchnet_account',
            old_name='ka_password',
            new_name='kn_password',
        ),
    ]
