# Generated by Django 3.0.7 on 2020-07-30 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200721_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата-время создания'),
            preserve_default=False,
        ),
    ]
