# Generated by Django 3.0.7 on 2020-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200807_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(verbose_name='Дата-время создания'),
        ),
    ]
