# Generated by Django 3.0.7 on 2020-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200807_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания'),
        ),
    ]
