# Generated by Django 3.0.7 on 2020-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200807_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerchnet_account',
            name='kn_datetime_created',
            field=models.DateTimeField(verbose_name='Дата-время создания'),
        ),
    ]
