# Generated by Django 3.0.7 on 2020-08-07 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200807_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime_created',
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата-время изменения'),
        ),
        migrations.AlterField(
            model_name='kerchnet_account',
            name='kn_datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата-время создания'),
        ),
    ]
