# Generated by Django 3.0.7 on 2020-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20200807_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_changed',
            field=models.DateTimeField(blank=True, verbose_name='Дата-время изменения'),
        ),
    ]
