# Generated by Django 3.0.7 on 2020-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200811_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_changed',
            field=models.DateTimeField(verbose_name='Дата-время изменения'),
        ),
    ]
