# Generated by Django 3.0.7 on 2020-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200811_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerchnet_account',
            name='kn_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
