# Generated by Django 3.1.3 on 2020-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200812_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerchnet_account',
            name='kn_state',
            field=models.BooleanField(default=False, verbose_name='Статус прорверки'),
        ),
    ]
