# Generated by Django 3.1.3 on 2020-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_kerchnet_account_kn_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerchnet_account',
            name='schedule_id',
            field=models.IntegerField(default=0),
        ),
    ]
